repository:
    path: github.com/shinhwagk/oracle_exporter
build:
    binaries:
        - name: oracle_exporter
    flags: -a -tags 'netgo osusergo static_build'
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
crossbuild:
    platforms:
        - linux