[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.6"

[[constraint]]
  name = "gopkg.in/goracle.v2"
  version = "2.5.9"

[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "gopkg.in/goracle.v2"
    unused-packages = false
