version: '3.4'

x-service: &sve
  image: shinhwagk/oracle_exporter:v1.0.9-yaml
  restart: 'on-failure'
  command:
    - '--file.metrics=http://gitlab.wexfin.com/oradba/prom-oracle/raw/master/metrics-11g.yaml'

services:
  prometheus:
    image: prom/prometheus:v2.25.0
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.external-url=http://localhost:9090/apps/prometheus/"
    volumes:
      - prometheus-config:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
  grafana:
     image: grafana/grafana:6.7.6
     environment:
       MYSQL_ROOT_PASSWORD: my-secret-pw
     ports:
       - 3001:3000
     volumes:
       - grafana-config:/etc/grafana
  grafana-mysql:
     image: mysql:8
     volumes:
        - grafana-mysql-storage:/var/lib/mysql
  gd_whmdb_whmdb_1_pr:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.10:1521/whmdb"
  gd_whmdb_whmdb_2_pr:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.11:1521/whmdb"
  gd_whmdb_whmdb_dgl_1_pr:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.17:1521/whmdb_dgl"
  gd_whmdb_whmdb_1_ps:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.12:1521/whmdb"
  gd_whmdb_whmdb_2_ps:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.13:1521/whmdb"
  gd_pmd_pmd_1_pr:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.26:1521/pmd"
  gd_pmd_pmd_2_pr:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.27:1521/pmd"
  gd_pmd_pmd_1_ps:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.22:1521/pmd"
  gd_pmd_pmd_2_ps:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.23:1521/pmd"
  gd_history_history_1_pr:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.38:1521/history"
  gd_arch_arch_1_pr:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.34:1521/arch"
  gd_arch_arch_2_pr:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.35:1521/arch"
  gd_zjtg_zjtg_1_pr:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.50:1521/zjtg"
  gd_zjtg_zjtg_2_pr:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.51:1521/zjtg"
  gd_zjtg_zjtg_1_ps:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.54:1521/zjtg"
  gd_zjtg_zjtg_2_ps:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.55:1521/zjtg"
  gd_zfjs_zfjs_1_pr:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.68:1521/zfjs"
  gd_zfjs_zfjs_2_pr:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.69:1521/zfjs"
  gd_zfjs_zfjs_1_ps:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.60:1521/zfjs"
  gd_zfjs_zfjs_2_ps:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.61:1521/zfjs"
  gq_dwdata_dwdata_1_pr:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.191.20:1521/dwdata"
  gq_dwdata_dwdata_2_pr:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.191.21:1521/dwdata"
  gd_fund_fund_1_pr:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.86:1521/fund"
  gd_fund_fund_2_pr:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.87:1521/fund"
  gd_fund_fund_1_ps:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.80:1521/fund"
  gd_fund_fund_2_ps:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.81:1521/fund"
  gd_escrow_escrow_1_pr:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.70:1521/escrow"
  gd_escrow_escrow_2_pr:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.71:1521/escrow"
  gd_escrow_escrow_1_ps:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.72:1521/escrow"
  gd_escrow_escrow_2_ps:
    <<: *sve
    environment:
      POE_DB_DATA_SOURCE: "${P_USERNAME}/${P_PASSWORD}@10.129.63.73:1521/escrow"
    command:
      - "--query.timeout=60"
 
volumes:
  prometheus-config:
    external: true
  prometheus-data:
    external: true
  nginx:
    external: true
  grafana-config:
    external: true
  grafana-mysql-storage:
    external: true