{
 "title": "log file sync",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "db_name",
    "query": "label_values(oracle_up, db_name)"
   },
   {
    "name": "inst",
    "query": "label_values(oracle_up{db_name=\"$db_name\"}, inst)"
   }
  ]
 },
 "panels": [
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "log file sync",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=\"$inst\", event=\"log file sync\"}[2m])",
     "legendFormat": "waited time"
    },
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=\"$inst\", event=\"log file sync\"}[2m])",
     "legendFormat": "waits"
    }
   ]
  },
  {
   "title": "log file sync",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=\"$inst\", event=\"log file sync\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=\"$inst\", event=\"log file sync\"}[2m])",
     "legendFormat": "pg - {{event}}"
    }
   ]
  },
  {
   "title": "log file parallel write",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=\"$inst\", event=\"log file parallel write\"}[2m])",
     "legendFormat": "waits"
    },
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=\"$inst\", event=\"log file parallel write\"}[2m])",
     "legendFormat": "waitd time"
    }
   ]
  },
  {
   "title": "log file parallel write -- avg/sec",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=\"$inst\", event=\"log file parallel write\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=\"$inst\", event=\"log file parallel write\"}[2m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "latch: redo allocation",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_pg_total{db_name=\"$db_name\", inst=\"$inst\", event=\"latch: redo allocation\"}[2m])",
     "legendFormat": "pg - waits"
    },
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=\"$inst\", event=\"latch: redo allocation\"}[2m])",
     "legendFormat": "waits"
    }
   ]
  },
  {
   "title": "latch: redo allocation",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waited_time_pg_total{db_name=\"$db_name\", inst=\"$inst\", event=\"latch: redo allocation\"}[2m]) / idelta(oracle_sysevent_waits_pg_total{db_name=\"$db_name\", inst=\"$inst\", event=\"latch: redo allocation\"}[2m])",
     "legendFormat": "pg - avg"
    },
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=\"$inst\", event=\"latch: redo allocation\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=\"$inst\", event=\"latch: redo allocation\"}[2m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "LGWR wait for redo copy",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=\"$inst\", event=\"LGWR wait for redo copy\"}[2m])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "LGWR wait for redo copy",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=\"$inst\", event=\"LGWR wait for redo copy\"}[2m])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "latch: redo copy",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waited_time_pg_total{db_name=\"$db_name\", inst=\"$inst\", event=\"latch: redo copy\"}[2m])",
     "legendFormat": "pg - {{event}}"
    },
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=\"$inst\", event=\"latch: redo copy\"}[2m])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "latch: redo copy",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_pg_total{db_name=\"$db_name\", inst=\"$inst\", event=\"latch: redo copy\"}[2m])",
     "legendFormat": "pg - {{event}}"
    },
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=\"$inst\", event=\"latch: redo copy\"}[2m])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "latch: redo writing",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=\"$inst\", event=\"latch: redo writing\"}[2m])",
     "legendFormat": "waits"
    },
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=\"$inst\", event=\"latch: redo writing\"}[2m])",
     "legendFormat": "waited time"
    }
   ]
  },
  {
   "title": "latch: redo writing",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=\"$inst\", event=\"latch: redo writing\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=\"$inst\", event=\"latch: redo writing\"}[2m])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "redo size [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"redo size\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "redo writes [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"redo writes\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Execute Count [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"execute count\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Commit / Rollback [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"user rollbacks\"}[2m])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"user commits\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "user calls [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"user calls\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "redo synch writes [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"redo synch writes\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "redo entries [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"redo entries\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "redo log space requests [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"redo log space requests\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "redo log space wait time [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "timeticks" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"redo log space wait time\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "redo synch long waits [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"redo synch long waits\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "transaction [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"user commits\"}[2m]), \"name\", \"\", \"name\", \".*\") + label_replace(idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"user rollbacks\"}[2m]), \"name\", \"\", \"name\", \".*\")",
     "legendFormat": "transaction"
    }
   ]
  },
  {
   "title": "redo synch polls [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"redo synch polls\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "redo write info find [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"redo write info find\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "redo synch time overhead count [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"redo synch time overhead count (<2 msec)\"}[2m])",
     "legendFormat": "{{name}} < 2 msec"
    },
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"redo synch time overhead count (<8 msec)\"}[2m])",
     "legendFormat": "{{name}} < 8 msec"
    },
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"redo synch time overhead count (<32 msec)\"}[2m])",
     "legendFormat": "{{name}} < 32 msec"
    },
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"redo synch time overhead count (<128 msec)\"}[2m])",
     "legendFormat": "{{name}} < 128 msec"
    },
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"redo synch time overhead count (>=128 msec)\"}[2m])",
     "legendFormat": "{{name}} >= 128 msec"
    },
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"redo synch time overhead (usec)\"}[2m])",
     "legendFormat": "{{name}} usec"
    }
   ]
  },
  {
   "title": "commit cleanout failures: block lost [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"commit cleanout failures: block lost\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "commit cleanout failures: write disabled [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"commit cleanout failures: write disabled\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "redo synch poll writes [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"redo synch poll writes\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "commit cleanout failures: buffer being written [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"commit cleanout failures: buffer being written\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "commit cleanout failures: cannot pin [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"commit cleanout failures: cannot pin\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "redo write info find fail [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=\"$inst\", name=\"redo write info find fail\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}