{
 "title": "node",
 "tags": [
  "prometheus",
  "node",
  "misc"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_load1{job=\"node\"}, instance)"
   },
   {
    "name": "filesystem_mountpoint",
    "query": "query_result(node_filesystem_size_bytes{job=\"node\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint!=\"/var/lib/docker/aufs\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "State",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"node\", instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{job=\"node\", instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by(cpu)(node_cpu_seconds_total{job=\"node\", instance=~\"$node:.*\"}))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\", instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "All disks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{job=\"node\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint!=\"/var/lib/docker/aufs\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"node\", instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "Cpu Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"node\", instance=~\"$node:.*\"}",
     "legendFormat": "load1"
    },
    {
     "expr": "node_load5{job=\"node\", instance=~\"$node:.*\"}",
     "legendFormat": "load5"
    },
    {
     "expr": "node_load15{job=\"node\", instance=~\"$node:.*\"}",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(mode)(irate(node_cpu_seconds_total{job=\"node\", instance=~\"$node:.*\", mode!=\"idle\"}[5m])) > 0",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Disk I/O utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{job=\"node\", instance=~\"$node:.*\", device!~\"dm-.*\"}[5m]) / 1000",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Buffers_bytes{job=\"node\", instance=~\"$node:.*\"}",
     "legendFormat": "buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node\", instance=~\"$node:.*\"}",
     "legendFormat": "cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node\", instance=~\"$node:.*\"}",
     "legendFormat": "free"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node\", instance=~\"$node:.*\"} - node_memory_MemFree_bytes{job=\"node\", instance=~\"$node:.*\"} - node_memory_Cached_bytes{job=\"node\", instance=~\"$node:.*\"} - node_memory_Buffers_bytes{job=\"node\", instance=~\"$node:.*\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node\", instance=~\"$node:.*\", device!~\"docker[0-9]|lo|bond[0-9]|cbr[0-9]|veth.*|br-.*\"}[2m])",
     "legendFormat": "{{device}} outbound"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node\", instance=~\"$node:.*\", device!~\"docker[0-9]|lo|bond[0-9]|cbr[0-9]|veth.*|br-.*\"}[2m])",
     "legendFormat": "{{device}} inbound"
    }
   ]
  },
  {
   "title": "Filesystem $filesystem_mountpoint usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "repeat": "filesystem_mountpoint",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"node\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint=\"$filesystem_mountpoint\"} - node_filesystem_free_bytes{job=\"node\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint=\"$filesystem_mountpoint\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_filesystem_free_bytes{job=\"node\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint=\"$filesystem_mountpoint\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Filesystem $filesystem_mountpoint usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"node\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint=\"$filesystem_mountpoint\"} - node_filesystem_free_bytes{job=\"node\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint=\"$filesystem_mountpoint\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_filesystem_free_bytes{job=\"node\", instance=~\"$node:.*\", device=~\"/dev/.*\", mountpoint=\"$filesystem_mountpoint\"}",
     "legendFormat": "free"
    }
   ]
  }
 ]
}