{
 "title": "Oracle SQL Detail",
 "tags": [
  "oracle",
  "sql",
  "detail"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "db_name",
    "label": "db_name",
    "query": "label_values(oracle_up, db_name)"
   },
   {
    "name": "inst",
    "query": "label_values(oracle_up{db_name=\"$db_name\"}, inst)"
   },
   {
    "name": "username",
    "label": "username",
    "query": "label_values(oracle_sql_executions_total{db_name=\"$db_name\", inst=\"$inst\"}, username)"
   },
   {
    "name": "sql_id",
    "label": "sql_id",
    "query": "label_values(oracle_sql_executions_total{db_name=\"$db_name\", inst=\"$inst\", username=\"$username\"}, sql_id)"
   },
   {
    "name": "child",
    "query": "label_values(oracle_sql_executions_total{db_name=\"$db_name\", inst=\"$inst\", username=\"$username\", sql_id=\"$sql_id\"}, child)"
   },
   {
    "name": "interval",
    "query": "2m,3m.4m,5m,10m,15m,20m,30m,1h,2h,3h,4h,6h,12h,1d,2d,3d,4d,5d,6d,7d,14d,30d"
   },
   {
    "name": "step",
    "query": "2m,3m,4m,5m,10m,15m,20m,30m,1h,2h,3h,4h,6h,12h,1d,2d,3d,4d,5d,6d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Sampling",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "oracle_sql_executions_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\", sql_id=\"$sql_id\"}"
    }
   ]
  },
  {
   "title": "Cpu Time [$interval / $step]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "increase(oracle_sql_cpu_time_total{db_name=\"$db_name\", inst=\"$inst\", sql_id=\"$sql_id\", username=\"$username\"}[$interval]) / increase(oracle_sql_executions_total{db_name=\"$db_name\", inst=\"$inst\", sql_id=\"$sql_id\", username=\"$username\"}[$interval])",
     "legendFormat": "{{child}}"
    },
    {
     "expr": "increase(oracle_sql_executions_total{db_name=\"$db_name\",inst=\"$inst\",sql_id=\"$sql_id\",username=\"$username\"}[$interval])",
     "legendFormat": "{{child}} - executions"
    }
   ]
  },
  {
   "title": "Cpu Time [$interval / $step]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 5 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sql_cpu_time_total{db_name=\"$db_name\", inst=\"$inst\", sql_id=\"$sql_id\", username=\"$username\"}[2m]) / idelta(oracle_sql_executions_total{db_name=\"$db_name\", inst=\"$inst\", sql_id=\"$sql_id\", username=\"$username\"}[2m])",
     "legendFormat": "{{child}}"
    },
    {
     "expr": "idelta(oracle_sql_executions_total{db_name=\"$db_name\",inst=\"$inst\",sql_id=\"$sql_id\",username=\"$username\"}[2m])",
     "legendFormat": "{{child}} - executions"
    }
   ]
  },
  {
   "title": "ASH Event [1m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(oracle_ash_sample{sql_id=\"$sql_id\", username=\"$username\", db_name=\"$db_name\", inst=\"$inst\"}) by (event)",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "elapsed time / executions [$interval]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "increase(oracle_sql_elapsed_time_total{db_name=\"$db_name\",inst=\"$inst\",sql_id=\"$sql_id\",username=\"$username\"}[$interval]) / increase(oracle_sql_executions_total{db_name=\"$db_name\",inst=\"$inst\",sql_id=\"$sql_id\",username=\"$username\"}[$interval])",
     "legendFormat": "{{child}} - per elapsed time"
    },
    {
     "expr": "increase(oracle_sql_executions_total{db_name=\"$db_name\",inst=\"$inst\",sql_id=\"$sql_id\",username=\"$username\"}[$interval])",
     "legendFormat": "{{child}} - executions"
    }
   ]
  },
  {
   "title": "Buffer Gets (per execute) [$interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(oracle_sql_buffer_gets_total{db_name=\"$db_name\",inst=\"$inst\",sql_id=\"$sql_id\",username=\"$username\"}[$interval]) / increase(oracle_sql_executions_total{db_name=\"$db_name\", inst=\"$inst\", sql_id=\"$sql_id\", username=\"$username\"}[$interval])",
     "legendFormat": "{{child}}"
    }
   ]
  },
  {
   "title": "User IO Wait / Executions [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 15 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "increase(oracle_sql_user_io_wait_total{db_name=\"$db_name\", inst=\"$inst\", sql_id=\"$sql_id\", child=~\"$child\", username=\"$username\"}[$interval]) / increase(oracle_sql_executions_total{db_name=\"$db_name\",inst=\"$inst\",sql_id=\"$sql_id\",child=~\"$child\",username=\"$username\"}[$interval])",
     "legendFormat": "{{child}} - user io wait"
    },
    {
     "expr": "increase(oracle_sql_executions_total{db_name=\"$db_name\",inst=\"$inst\",sql_id=\"$sql_id\",child=~\"$child\",username=\"$username\"}[$interval])",
     "legendFormat": "{{child}} - executions"
    }
   ]
  },
  {
   "title": "Rows Processed (per execute) [1m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sql_rows_processed_total{db_name=\"$db_name\",inst=\"$inst\",sql_id=\"$sql_id\",username=\"$username\"}[2m]) / idelta(oracle_sql_executions_total{db_name=\"$db_name\",inst=\"$inst\",sql_id=\"$sql_id\",username=\"$username\"}[2m])",
     "legendFormat": "{{child}}"
    }
   ]
  },
  {
   "title": "Application IO Wait / Executions [$interval]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 20 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "increase(oracle_sql_application_wait_total{db_name=\"$db_name\", inst=\"$inst\", sql_id=\"$sql_id\", child=~\"$child\", username=\"$username\"}[$interval]) / increase(oracle_sql_executions_total{db_name=\"$db_name\",inst=\"$inst\",sql_id=\"$sql_id\",child=~\"$child\",username=\"$username\"}[$interval])",
     "legendFormat": "{{child}} - application io wait"
    },
    {
     "expr": "increase(oracle_sql_executions_total{db_name=\"$db_name\",inst=\"$inst\",sql_id=\"$sql_id\",child=~\"$child\",username=\"$username\"}[$interval])",
     "legendFormat": "{{child}} - executions"
    }
   ]
  },
  {
   "title": "Sort (per execute) [$interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(oracle_sql_sort_total{db_name=\"$db_name\", inst=\"$inst\", sql_id=\"$sql_id\", username=\"$username\"}[$interval]) / delta(oracle_sql_executions_total{db_name=\"$db_name\", inst=\"$inst\", sql_id=\"$sql_id\", username=\"$username\"}[$interval])",
     "legendFormat": "{{child}}"
    }
   ]
  },
  {
   "title": "Cluster Wait / Executions [$interval]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 25 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "increase(oracle_sql_cluster_wait_total{db_name=\"$db_name\", inst=\"$inst\", sql_id=\"$sql_id\", child=~\"$child\", username=\"$username\"}[$interval]) / increase(oracle_sql_executions_total{db_name=\"$db_name\",inst=\"$inst\",sql_id=\"$sql_id\",child=~\"$child\",username=\"$username\"}[$interval])",
     "legendFormat": "{{child}} - avg"
    },
    {
     "expr": "increase(oracle_sql_executions_total{db_name=\"$db_name\",inst=\"$inst\",sql_id=\"$sql_id\",child=~\"$child\",username=\"$username\"}[$interval])",
     "legendFormat": "{{child}} - executions"
    }
   ]
  },
  {
   "title": "Concurrency Wait / Executions [$interval]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 30 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "increase(oracle_sql_concurrency_wait_total{db_name=\"$db_name\", inst=\"$inst\", sql_id=\"$sql_id\", username=\"$username\"}[$interval]) / increase(oracle_sql_executions_total{db_name=\"$db_name\",inst=\"$inst\",sql_id=\"$sql_id\",username=\"$username\"}[$interval])",
     "legendFormat": "{{child}} - avg"
    },
    {
     "expr": "increase(oracle_sql_executions_total{db_name=\"$db_name\",inst=\"$inst\",sql_id=\"$sql_id\",username=\"$username\"}[$interval])",
     "legendFormat": "{{child}} - executions"
    }
   ]
  },
  {
   "title": "Parse Call",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(oracle_sql_parse_call_total{db_name=\"$db_name\",inst=\"$inst\",sql_id=\"$sql_id\",username=\"$username\"}[$interval])",
     "legendFormat": "{{child}}"
    }
   ]
  },
  {
   "title": "Phys Read [$interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "increase(oracle_sql_phy_read_bytes_total{db_name=\"$db_name\",inst=\"$inst\",sql_id=\"$sql_id\",username=\"$username\"}[$interval]) ",
     "legendFormat": "bytes - {{child}}"
    },
    {
     "expr": "increase(oracle_sql_executions_total{db_name=\"$db_name\",inst=\"$inst\",sql_id=\"$sql_id\",username=\"$username\"}[$interval])",
     "legendFormat": "req - {{child}}"
    }
   ]
  },
  {
   "title": "SQL Xplan",
   "type": "text",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 41 },
   "content": "<script>\r\n  var callback = function(data) {\r\n    $(\"#xplan\").text(data.xplan) ;\r\n  };\r\n</script>\r\n<script src=\"/xplan?db_name=${db_name}&inst=${inst}&sql_id=${sql_id}&child=${child}\"></script>\r\n<pre><span id=\"xplan\" /></pre>"
  }
 ]
}