{
 "title": "Oracle Overview",
 "description": "oracledb dashboard",
 "tags": [
  "oracle",
  "overview"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "db_name",
    "query": "label_values(oracle_up, db_name)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "2m,10m,30m,1h,2h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "DB Time for Schema",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_sesstat_dbtime_total{db_name=\"$db_name\"}[2m])) by (username, inst) > 0 ",
     "legendFormat": "{{inst}} - {{username}}"
    }
   ]
  },
  {
   "title": "DB Time for Schema($interval)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(delta(oracle_sesstat_dbtime_total{db_name=\"$db_name\"}[$interval])) by (username, inst) > 0 "
    }
   ]
  },
  {
   "title": "DB Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysstat_dbtime_total{db_name=\"$db_name\"}[2m])",
     "legendFormat": "{{inst}}"
    }
   ]
  },
  {
   "title": "Session / Active Session",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(oracle_session{db_name=\"$db_name\", status=\"ACTIVE\", type=\"USER\", username != \"null\"}) by (inst)",
     "legendFormat": "active- {{inst}}"
    },
    {
     "expr": "sum(oracle_session{db_name=\"$db_name\"}) by (inst)",
     "legendFormat": "total-{{inst}}"
    },
    {
     "expr": "ceil(sum(oracle_ash_sample{db_name=\"$db_name\"}) by (inst) / 60)",
     "legendFormat": "ash avg-{{inst}}"
    }
   ]
  },
  {
   "title": "Top System Event ($interval)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "delta(oracle_sysevent_waits_total{db_name=\"$db_name\", class!=\"Idle\"}[$interval]) > 0",
     "legendFormat": "waits"
    },
    {
     "expr": "delta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", class!=\"Idle\"}[$interval]) > 0"
    },
    {
     "expr": "delta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", class!=\"Idle\"}[$interval]) / delta(oracle_sysevent_waits_total{db_name=\"$db_name\", class!=\"Idle\"}[$interval]) > 0"
    }
   ]
  },
  {
   "title": "System Event ( per wait time)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", class!=\"Idle\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", class!=\"Idle\"}[2m])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Ash Event",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(oracle_ash_sample{db_name=\"$db_name\", event!=\"Wait for CPU\"}) by(inst,event,username,sql_id)"
    }
   ]
  },
  {
   "title": "Session Connect",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "oracle_session{db_name=\"$db_name\"}"
    }
   ]
  },
  {
   "title": "ASH Event",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(oracle_ash_sample{db_name=\"$db_name\", event!~\"null|Wait for CPU\"}) by(event, inst)",
     "legendFormat": "{{inst}} - {{event}}"
    },
    {
     "expr": "sum(oracle_ash_sample{db_name=\"$db_name\", event=\"Wait for CPU\"}) by(event, inst)",
     "legendFormat": "cpu - {{inst}} - {{event}}"
    }
   ]
  },
  {
   "title": "redo size/s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(oracle_sysstat_redo_total{db_name=\"$db_name\"}[2m])",
     "legendFormat": "{{inst}}"
    }
   ]
  },
  {
   "title": "Commit & Rollback Per 1 Min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysstat_commit_total{db_name=\"$db_name\"}[2m])",
     "legendFormat": "{{inst}} - commit"
    },
    {
     "expr": "idelta(oracle_sysstat_rollback_total{db_name=\"$db_name\"}[2m])",
     "legendFormat": "{{inst}} - rollback"
    }
   ]
  },
  {
   "title": "System Command Executions State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_sql_executions_total{db_name=\"$db_name\"}[2m])) by (command,inst)",
     "legendFormat": "{{inst}} - {{command}}"
    }
   ]
  },
  { "title": "Widgets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }, "repeat": "db_name" },
  {
   "title": "SQL Elapsed Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "topk(5, idelta(oracle_sql_elapsed_time_total{db_name=\"$db_name\"}[5m]) / idelta(oracle_sql_executions_total{db_name=\"$db_name\"}[5m]) > 100000)",
     "legendFormat": "{{inst}} - {{username}} - {{sql_id}}"
    }
   ]
  },
  {
   "title": "Heatmap on Elapsed Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "idelta(oracle_sql_elapsed_time_total{db_name=\"$db_name\"}[3m]) / idelta(oracle_sql_executions_total{db_name=\"$db_name\"}[3m])"
    }
   ]
  },
  { "title": "system statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Read/Write Bytes Total / 1 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysstat_phy_read_bytes_total{db_name=\"$db_name\"}[3m])",
     "legendFormat": "{{inst}} - read bytes"
    },
    {
     "expr": "idelta(oracle_sysstat_phy_write_bytes_total{db_name=\"$db_name\"}[3m])",
     "legendFormat": "{{inst}} - write bytes"
    }
   ]
  },
  {
   "title": "Read/Write total / 1 min / per transaction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(idelta(oracle_sysstat_phy_read_bytes_total{db_name=\"$db_name\"}[3m]),\"class\",\"\" ,\"class\",\".*\") / label_replace(idelta(oracle_sysstat_commit_total{db_name=\"$db_name\"}[3m]) + idelta(oracle_sysstat_rollback_total{db_name=\"$db_name\"}[3m]),\"class\",\"\" ,\"class\",\".*\")",
     "legendFormat": "{{inst}} - read bytes / per transaction"
    },
    {
     "expr": "label_replace(idelta(oracle_sysstat_phy_write_bytes_total{db_name=\"$db_name\"}[3m]),\"class\",\"\" ,\"class\",\".*\") / label_replace(idelta(oracle_sysstat_commit_total{db_name=\"$db_name\"}[3m]) + idelta(oracle_sysstat_rollback_total{db_name=\"$db_name\"}[3m]),\"class\",\"\" ,\"class\",\".*\")",
     "legendFormat": "{{inst}} - write bytes / per transaction"
    }
   ]
  },
  {
   "title": "Parser Soft Hard",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysstat_parse_total{db_name=\"$db_name\"}[2m]) - idelta(oracle_sysstat_parse_hard_total{db_name=\"$db_name\"}[2m])",
     "legendFormat": "{{inst}}"
    }
   ]
  },
  {
   "title": "Parser Hard",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysstat_parse_hard_total{db_name=\"$db_name\"}[2m])",
     "legendFormat": "{{inst}}"
    }
   ]
  },
  {
   "title": "Parser Failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysstat_parse_failures_total{db_name=\"$db_name\"}[2m])",
     "legendFormat": "{{inst}}"
    }
   ]
  },
  {
   "title": "Execute to Parse %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (idelta(oracle_sysstat_parse_total{db_name=\"$db_name\"}[3m]) / idelta(oracle_sysstat_execute_total{db_name=\"$db_name\"}[3m]))) * 100",
     "legendFormat": "{{inst}}"
    }
   ]
  },
  {
   "title": "Physical Reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysstat_physicalreads_total{db_name=\"$db_name\", inst=\"$inst\"}[3m])"
    },
    {
     "expr": "idelta(oracle_sysstat_physicalreads_total{db_name=\"$db_name\", inst=\"$inst\"}[3m]) / (idelta(oracle_sysstat_commit_total{db_name=\"$db_name\", inst=\"$inst\"}[2m]) + idelta(oracle_sysstat_rollback_total{db_name=\"$db_name\", inst=\"$inst\"}[2m]))",
     "legendFormat": "per transaction"
    }
   ]
  },
  {
   "title": "Physical Writes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysstat_physicalwrites_total{db_name=\"$db_name\", inst=\"$inst\"}[2m])"
    },
    {
     "expr": "idelta(oracle_sysstat_physicalwrites_total{db_name=\"$db_name\", inst=\"$inst\"}[2m]) / (idelta(oracle_sysstat_commit_total{db_name=\"$db_name\", inst=\"$inst\"}[2m]) + idelta(oracle_sysstat_rollback_total{db_name=\"$db_name\", inst=\"$inst\"}[2m]))",
     "legendFormat": "per tramsactopm"
    }
   ]
  },
  {
   "title": "User Calls",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysstat_useralls_total{db_name=\"$db_name\", inst=\"$inst\"}[2m])"
    },
    {
     "expr": "idelta(oracle_sysstat_useralls_total{db_name=\"$db_name\", inst=\"$inst\"}[2m]) / (idelta(oracle_sysstat_commit_total{db_name=\"$db_name\", inst=\"$inst\"}[2m]) + idelta(oracle_sysstat_rollback_total{db_name=\"$db_name\", inst=\"$inst\"}[2m]))",
     "legendFormat": "per transaction"
    }
   ]
  }
 ]
}