{
 "title": "Oracle User",
 "tags": [
  "oracle",
  "user"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "db_name",
    "label": "db_name",
    "query": "label_values(oracle_up, db_name)"
   },
   {
    "name": "inst",
    "query": "label_values(oracle_up{db_name=\"$db_name\"}, inst)"
   },
   {
    "name": "username",
    "label": "username",
    "query": "label_values(oracle_sql_executions_total{db_name=\"$db_name\", inst=\"$inst\"}, username)"
   },
   {
    "name": "interval",
    "query": "2m,3m,4m,5m,10m,15m,20m,30m,40m,50m,1h,2h,3h,4h,5h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Command Status Executes [$interval]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(oracle_sql_executions_total{db_name=\"$db_name\", inst=\"$inst\", username=\"$username\"}[$interval])) by (inst,command)",
     "legendFormat": "{{inst}}-{{command}}"
    }
   ]
  },
  {
   "title": "DB time [1min]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_sesstimemodel_db_time{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[2m])) by(username)",
     "legendFormat": "db time"
    }
   ]
  },
  {
   "title": "Top elapsed time [$interval]",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": " increase(oracle_sql_elapsed_time_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[$interval]) and changes(oracle_sql_executions_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[$interval]) >= 2"
    },
    {
     "expr": "increase(oracle_sql_executions_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[$interval]) and changes(oracle_sql_executions_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[$interval]) >= 2"
    },
    {
     "expr": "increase(oracle_sql_elapsed_time_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[$interval]) / (increase(oracle_sql_executions_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[$interval]) and changes(oracle_sql_executions_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[$interval]) >= 2)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Executeions [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_sesstat_execute_total{db_name=\"$db_name\", inst=\"$inst\", username=\"$username\"}[2m]))",
     "legendFormat": "{{inst}}"
    }
   ]
  },
  {
   "title": "Session / Active Session [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(oracle_ash_sample{db_name=\"$db_name\", inst=\"$inst\", username=\"$username\"})",
     "legendFormat": "ash - {{inst}}"
    }
   ]
  },
  {
   "title": "Top User Event ($interval)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(increase(oracle_sessevent_waited_time_total{db_name=\"$db_name\", class!=\"Idle\", inst=~\"$inst\", username=\"$username\"}[$interval])) by (event) > 0",
     "legendFormat": "waits"
    },
    {
     "expr": "sum(increase(oracle_sessevent_waits_total{db_name=\"$db_name\", class!=\"Idle\", inst=~\"$inst\", username=\"$username\"}[$interval])) by (event) > 0"
    },
    {
     "expr": "(sum(increase(oracle_sessevent_waited_time_total{db_name=\"$db_name\", class!=\"Idle\", inst=~\"$inst\", username=\"$username\"}[$interval])) by (event)) / (sum(increase(oracle_sessevent_waits_total{db_name=\"$db_name\", class!=\"Idle\", inst=~\"$inst\", username=\"$username\"}[$interval])) by (event) >= 1)"
    }
   ]
  },
  {
   "title": "Commit / Rollback [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_sesstat_commit_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[2m]))",
     "legendFormat": "commit"
    },
    {
     "expr": "sum(idelta(oracle_sesstat_rollback_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[2m]))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Redo / Rate [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_sesstat_redo_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[2m]))",
     "legendFormat": "per min"
    },
    {
     "expr": "sum(irate(oracle_sesstat_redo_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[2m]))",
     "legendFormat": "per sec"
    }
   ]
  },
  {
   "title": "Parse Total [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(oracle_sesstat_parse_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[10m]))",
     "legendFormat": "number"
    }
   ]
  },
  {
   "title": "Session Wait",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(increase(oracle_sessevent_waited_time_total{db_name=\"$db_name\", username=\"$username\", class!=\"Idle\", inst=\"$inst\"}[2m])) by (event) / (sum(increase(oracle_sessevent_waits_total{db_name=\"$db_name\", username=\"$username\", class!=\"Idle\", inst=\"$inst\"}[2m])) by (event) > 0)",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Session Wait [$interval]",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "increase(oracle_sessevent_waited_time_total{db_name=\"$db_name\", username=\"$username\", class!=\"Idle\", inst=\"$inst\"}[$interval]) / (increase(oracle_sessevent_waits_total{db_name=\"$db_name\", username=\"$username\", class!=\"Idle\", inst=\"$inst\"}[$interval]) and changes(oracle_sessevent_waits_total{db_name=\"$db_name\", username=\"$username\", class!=\"Idle\", inst=\"$inst\"}[$interval]) >= 2)"
    },
    {
     "expr": "increase(oracle_sessevent_waits_total{db_name=\"$db_name\", username=\"$username\", class!=\"Idle\", inst=\"$inst\"}[$interval]) and changes(oracle_sessevent_waits_total{db_name=\"$db_name\", username=\"$username\", class!=\"Idle\", inst=\"$inst\"}[$interval]) >= 2"
    }
   ]
  },
  {
   "title": "Execute to Parse %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - sum(idelta(oracle_sesstat_parse_total{db_name=\"$db_name\", username=\"$username\", inst=~\"$inst\"}[3m]) / idelta(oracle_sesstat_execute_total{db_name=\"$db_name\", username=\"$username\", inst=~\"$inst\"}[3m])) by (username, inst)) * 100",
     "legendFormat": "{{inst}}"
    }
   ]
  },
  {
   "title": "Parse Total [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(oracle_sesstat_parse_hard_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[10m]))",
     "legendFormat": "number"
    }
   ]
  },
  {
   "title": "Long Session rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(oracle_sesstat_dbtime_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"})"
    },
    {
     "expr": "sum(oracle_session{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"})"
    }
   ]
  }
 ]
}