{
 "title": "Oracle ASH",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "db_name",
    "query": "label_values(oracle_up, db_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "ASH Analytics",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(oracle_ash_wait_class{db_name=\"$db_name\"}) by(class)",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "ASH  Overview",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(oracle_ash_wait_class{db_name=\"$db_name\"}) by(class)",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Event",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(oracle_ash_wait_class{db_name=\"$db_name\", event!=\"null\"}) by(event)",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "sql_id",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(oracle_ash_wait_class{db_name=\"$db_name\"}) by(sql_id,username))",
     "legendFormat": "{{sql_id}}"
    }
   ]
  },
  {
   "title": "User",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(20, sum(oracle_ash_wait_class{db_name=\"$db_name\"}) by (username))",
     "legendFormat": "{{username}}"
    }
   ]
  }
 ]
}