{
 "title": "Oracle User",
 "tags": [
  "oracle",
  "user"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "db_name",
    "label": "db_name",
    "query": "label_values(oracle_up, db_name)"
   },
   {
    "name": "username",
    "label": "username",
    "query": "label_values(oracle_sql_executions_total{db_name=\"$db_name\"}, username)"
   },
   {
    "name": "object_type",
    "query": "label_values(oracle_object_total{db_name=\"$db_name\", username=\"$username\"}, object_type)"
   }
  ]
 },
 "panels": [
  { "title": "Username", "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "# $db_name $username" },
  {
   "title": "Active Session",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current"
  },
  {
   "title": "redo size/s",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "idelta(oracle_sesstat_redo_total{db_name=\"$db_name\", username=\"[[username]]USER\"}[2m]) / 60"
    }
   ]
  },
  {
   "title": "Objects",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "oracle_object_total{db_name=\"$db_name\", username=~\"$username|[[username]]USER\"}"
    }
   ]
  },
  {
   "title": "Top Event",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "expr": " topk(8, idelta(oracle_sessevent_waited_time_total{db_name=\"$db_name\", username=\"[[username]]USER\", class!=\"Idle\"}[2m]) / idelta(oracle_sessevent_waits_total{db_name=\"$db_name\", username=\"[[username]]USER\", class!=\"Idle\"}[2m]))"
    }
   ]
  },
  {
   "title": "Heatmap on Elapsed Time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "idelta(oracle_sql_elapsed_time_total{db_name=\"$db_name\", username=\"[[username]]USER\"}[3m]) / idelta(oracle_sql_executions_total{db_name=\"$db_name\", username=\"[[username]]USER\"}[3m]) > 0"
    }
   ]
  },
  {
   "title": "Commit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "repeat": "username",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sesstat_commit_total{db_name=\"$db_name\", username=\"[[username]]USER\"}[2m]) > 0"
    }
   ]
  },
  {
   "title": "Redo",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "repeat": "username",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sesstat_redo_total{db_name=\"$db_name\", username=\"[[username]]USER\"}[2m]) > 0",
     "legendFormat": "{{username}}"
    },
    {
     "expr": "idelta(oracle_sesstat_redo_total{db_name=\"$db_name\", username=\"[[username]]USER\"}[2m]) / 60"
    }
   ]
  }
 ]
}