{
 "title": "Oracle User Wait",
 "tags": [
  "oracle",
  "event",
  "wait",
  "user"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "db_name",
    "query": "label_values(oracle_up, db_name)"
   },
   {
    "name": "inst",
    "query": "label_values(oracle_up{db_name=\"$db_name\"}, inst)"
   },
   {
    "name": "username",
    "query": "label_values(oracle_sessevent_waited_time_total{db_name=\"$db_name\", inst=\"$inst\"},username)"
   },
   {
    "name": "class",
    "query": "label_values(oracle_sessevent_waited_time_total{db_name=\"$db_name\", inst=\"$inst\", username=\"$username\"}, class)"
   },
   {
    "name": "event",
    "label": "event",
    "query": "label_values(oracle_sessevent_waited_time_total{db_name=\"$db_name\", inst=\"$inst\", class=~\"$class\" , username=\"$username\"}, event)"
   }
  ]
 },
 "panels": [
  {
   "title": "Long Session Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(oracle_sesstat_dbtime_total{db_name=\"$db_name\", inst=\"$inst\", username=\"$username\"})",
     "legendFormat": "long session"
    },
    {
     "expr": "sum(oracle_session{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"})",
     "legendFormat": "current session"
    }
   ]
  },
  {
   "title": "Class [1m]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_sessevent_waited_time_total{db_name=\"$db_name\", inst=\"$inst\", class!=\"Idle\", username=\"$username\"}[2m])) by (class) / sum(idelta(oracle_sessevent_waits_total{db_name=\"$db_name\", inst=\"$inst\", class!=\"Idle\", username=\"$username\"}[2m])) by (class)",
     "legendFormat": "avg - {{class}}"
    }
   ]
  },
  {
   "title": "$class - $event",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "repeat": "event",
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_sessevent_waits_total{db_name=\"$db_name\", inst=\"$inst\", event=~\"$event\",username=\"$username\"}[2m])) by (event)",
     "legendFormat": "time"
    },
    {
     "expr": "(sum(idelta(oracle_sessevent_waited_time_total{db_name=\"$db_name\", class!=\"Idle\", inst=\"$inst\", username=\"$username\", event=\"$event\"}[2m])) by (event)) / (sum(idelta(oracle_sessevent_waits_total{db_name=\"$db_name\", class!=\"Idle\", inst=\"$inst\", username=\"$username\", event=\"$event\"}[2m])) by (event) > 0)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Ash Events",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(oracle_ash_sample{db_name=\"$db_name\", inst=~\"$inst\", event=~\"$event\", username=\"$username\"}) by (event,sql_id)",
     "legendFormat": "{{event}} - {{sql_id}}"
    }
   ]
  }
 ]
}