{
 "title": "Oracle SQL Statistics",
 "tags": [
  "oracle",
  "sql"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "db_name",
    "query": "label_values(oracle_up, db_name)"
   },
   {
    "name": "inst",
    "query": "label_values(oracle_up{db_name=\"$db_name\"},inst)"
   },
   {
    "name": "parsing_schema",
    "query": "label_values(oracle_sql_cpu_time_total{db_name=\"$db_name\", inst=\"$inst\"}, username)"
   },
   {
    "name": "interval",
    "query": "10m,15m,20m,30m,1h,2h,3h,4h,5h,6h,7h,8h,9h,10h,11h,12h,1d,2d,3d,4d,5d,6d,,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Sql [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(oracle_sql_executions_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}) by (inst)",
     "legendFormat": "{{inst}}"
    }
   ]
  },
  {
   "title": "Execute Total [1m]",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_sql_executions_total{db_name=\"$db_name\", inst=\"$inst\", username=~\"$parsing_schema\"}[2m])) by (command)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "SQL ordered by Elapsed Time [$interval]",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(oracle_sql_elapsed_time_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) and changes(oracle_sql_executions_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) >= 2"
    },
    {
     "expr": "increase(oracle_sql_elapsed_time_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) / (increase(oracle_sql_executions_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) and changes(oracle_sql_executions_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) >= 2)"
    },
    {
     "expr": "increase(oracle_sql_executions_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) and changes(oracle_sql_executions_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) >= 2"
    }
   ]
  },
  {
   "title": "SQL ordered by Gets [$interval]",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(oracle_sql_buffer_gets_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) and changes(oracle_sql_executions_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) >= 2"
    },
    {
     "expr": "(increase(oracle_sql_buffer_gets_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) and changes(oracle_sql_executions_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) >= 2 ) / (increase(oracle_sql_executions_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) and changes(oracle_sql_executions_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) >= 2)"
    },
    {
     "expr": "increase(oracle_sql_executions_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) and changes(oracle_sql_executions_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) >= 2"
    }
   ]
  },
  {
   "title": "SQL ordered by CPU Time [$interval]",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "increase(oracle_sql_cpu_time_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval])"
    },
    {
     "expr": "increase(oracle_sql_cpu_time_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) / increase(oracle_sql_executions_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval])"
    },
    {
     "expr": "increase(oracle_sql_executions_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval])"
    },
    {
     "expr": "changes(oracle_sql_executions_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) >= 1"
    }
   ]
  },
  {
   "title": "SQL ordered by Sort [$interval]",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "increase(oracle_sql_sort_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval])"
    },
    {
     "expr": "increase(oracle_sql_sort_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) / increase(oracle_sql_executions_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval])"
    },
    {
     "expr": "increase(oracle_sql_executions_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval])"
    },
    {
     "expr": "changes(oracle_sql_executions_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) >= 1"
    }
   ]
  },
  {
   "title": "SQL ordered by Disk Read [$interval]",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "increase(oracle_sql_disk_read_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) and changes(oracle_sql_disk_read_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) >= 2"
    }
   ]
  },
  {
   "title": "SQL ordered by Executions [$interval]",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "increase(oracle_sql_executions_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) and changes(oracle_sql_executions_total{db_name=~\"$db_name\", inst=~\"$inst\", username=~\"$parsing_schema\"}[$interval]) >= 2"
    }
   ]
  }
 ]
}