{
 "title": "Oracle System Wait Event",
 "tags": [
  "oracle",
  "event",
  "wait",
  "system"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "db_name",
    "query": "label_values(oracle_up, db_name)"
   },
   {
    "name": "inst",
    "query": "label_values(oracle_up{db_name=\"$db_name\"}, inst)"
   },
   {
    "name": "class",
    "query": "label_values(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=\"$inst\"}, class)"
   },
   {
    "name": "event",
    "label": "event",
    "query": "label_values(oracle_sysevent_waits_total{db_name=\"$db_name\",inst=~\"$inst\", class=~\"$class\"}, event)"
   }
  ]
 },
 "panels": [
  {
   "title": "Class Avg [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=\"$inst\", class!=\"Idle\"}[2m])) by (class) / sum(idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=\"$inst\", class!=\"Idle\"}[2m])) by (class)",
     "legendFormat": "avg - {{class}}"
    }
   ]
  },
  {
   "title": "Class Time [1m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=\"$inst\", class!=\"Idle\"}[2m])) by (class)",
     "legendFormat": "class - {{class}}"
    }
   ]
  },
  {
   "title": "Class Count [1m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=\"$inst\", class!=\"Idle\"}[2m])) by (class)",
     "legendFormat": "avg - {{class}}"
    }
   ]
  },
  {
   "title": "$event",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "repeat": "event",
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "times"
    },
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$event",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "times"
    },
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$event",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "times"
    },
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$event",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "times"
    },
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$event",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "times"
    },
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$event",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "times"
    },
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$event",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "times"
    },
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$event",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "times"
    },
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$event",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "times"
    },
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$event",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "times"
    },
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$event",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "times"
    },
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$event",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "times"
    },
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$event",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "times"
    },
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$event",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "times"
    },
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$event",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "times"
    },
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "$event",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "times"
    },
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", inst=~\"$inst\", event=\"$event\"}[2m])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Ash Events",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(oracle_ash_sample{db_name=\"$db_name\", inst=\"$inst\", event=~\"$event\"}) by(username, event, sql_id)",
     "legendFormat": "{{username}} - {{event}} - {{sql_id}}"
    }
   ]
  },
  {
   "title": "Ash Events",
   "type": "graph",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(oracle_ash_sample{db_name=\"$db_name\", inst=\"$inst\"}) by(event)",
     "legendFormat": "{{event}} "
    }
   ]
  }
 ]
}