{
 "title": "Oracle Active Session Alert",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Oracle Active Session",
   "type": "graph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(oracle_active_session_max_seconds)",
     "legendFormat": "{{db_name}} - {{inst}}"
    }
   ]
  },
  {
   "title": "Oracle Active Session For User",
   "type": "graph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(oracle_active_session_user_max_seconds) >= 30",
     "legendFormat": "{{db_name}} - {{inst}} - {{username}}"
    }
   ]
  },
  {
   "title": "Oracle Active Session AVG [1m]",
   "type": "graph",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(sum(oracle_ash_sample)by(db_name,inst,sample_id))by(db_name,inst)",
     "legendFormat": "{{db_name}} - {{inst}}"
    }
   ]
  }
 ]
}