{
 "title": "Oracle Overview",
 "description": "oracledb dashboard",
 "tags": [
  "oracle",
  "overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "db_name",
    "query": "label_values(oracle_up, db_name)"
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "query": "label_values(oracledb_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "oracledb status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracle_up{db_name=\"$db_name\", job=\"oracle\"}"
    }
   ]
  },
  {
   "title": "active sessions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(oracle_sessions_activity{status='ACTIVE', db_name=\"$db_name\", type=\"USER\"})"
    }
   ]
  },
  {
   "title": "DB Time for schema",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sort(topk(10, idelta(oracle_sesstat_dbtime_total{db_name=\"$db_name\"}[2m])))",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "user commits",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "idelta(oracle_sysstat_commit_total{db_name=\"$db_name\"}[2m])"
    }
   ]
  },
  {
   "title": "redo size/s",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "idelta(oracle_sysstat_redo_total{db_name=\"$db_name\"}[2m]) / 60"
    }
   ]
  },
  {
   "title": "DB Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysstat_dbtime_total{db_name=\"$db_name\"}[3m])"
    }
   ]
  },
  {
   "title": "Top Event 8",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": " topk(8, idelta(oracle_sysevent_waited_time_total{db_name=\"$db_name\", class!=\"Idle\"}[2m]) / idelta(oracle_sysevent_waits_total{db_name=\"$db_name\", class!=\"Idle\"}[2m]))"
    }
   ]
  },
  {
   "title": "Session total/active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(oracle_sessions_activity{status='ACTIVE', db_name=\"$db_name\", type=\"USER\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(oracle_sessions_activity{ db_name=\"$db_name\", type=\"USER\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Widgets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "repeat": "db_name",
   "collapsed": true,
   "panels": [
    {
     "title": "SQL Elapsed Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "topk(5, idelta(oracle_sql_elapsed_time_total{db_name=\"$db_name\"}[5m]) / idelta(oracle_sql_executions_total{db_name=\"$db_name\"}[5m]) > 100000)",
       "legendFormat": "{{sql_id}}"
      }
     ]
    },
    {
     "title": "Heatmap on Elapsed Time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "idelta(oracle_sql_elapsed_time_total{db_name=\"$db_name\"}[3m]) / idelta(oracle_sql_executions_total{db_name=\"$db_name\"}[3m]) > 0"
      }
     ]
    },
    {
     "title": "Commit & Rollback Per 1 Min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "idelta(oracle_sysstat_commit_total{db_name=\"$db_name\"}[2m])",
       "legendFormat": "commit"
      },
      {
       "expr": "idelta(oracle_sysstat_rollback_total{db_name=\"$db_name\"}[2m])",
       "legendFormat": "rollback"
      }
     ]
    }
   ]
  },
  {
   "title": "Load Profile",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "repeat": "db_name",
   "collapsed": true,
   "panels": [
    {
     "title": "Read/Write Bytes Total / 1 min",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "idelta(oracle_sysstat_logicalwrite_bytes_total{db_name=\"$db_name\"}[20m])",
       "legendFormat": "write bytes"
      },
      {
       "expr": "idelta(oracle_sysstat_logicalread_bytes_total{db_name=\"$db_name\"}[20m])",
       "legendFormat": "read bytes"
      }
     ]
    },
    {
     "title": "Read/Write total / 1 min / per transaction",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "idelta(oracle_sysstat_logicalread_bytes_total{db_name=\"$db_name\"}[2m]) / (idelta(oracle_sysstat_commit_total{db_name=\"$db_name\"}[2m]) + idelta(oracle_sysstat_rollback_total{db_name=\"$db_name\"}[2m]))",
       "legendFormat": "read bytes / per transaction"
      },
      {
       "expr": "idelta(oracle_sysstat_logicalwrite_bytes_total{db_name=\"$db_name\"}[2m]) / (idelta(oracle_sysstat_commit_total{db_name=\"$db_name\"}[2m]) + idelta(oracle_sysstat_rollback_total{db_name=\"$db_name\"}[2m]))",
       "legendFormat": "write bytes / per transaction"
      }
     ]
    },
    {
     "title": "Redo size",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "idelta(oracle_sysstat_redo_total{db_name=\"$db_name\"}[3m])"
      },
      {
       "expr": "idelta(oracle_sysstat_redo_total{db_name=\"$db_name\"}[2m]) / (idelta(oracle_sysstat_commit_total{db_name=\"$db_name\"}[2m]) + idelta(oracle_sysstat_rollback_total{db_name=\"$db_name\"}[2m]))",
       "legendFormat": "per transaction"
      }
     ]
    },
    {
     "title": "Logical Reads",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "idelta(oracle_sysstat_logicalreads_total{db_name=\"$db_name\"}[3m])"
      },
      {
       "expr": "idelta(oracle_sysstat_logicalreads_total{db_name=\"$db_name\"}[3m]) / (idelta(oracle_sysstat_commit_total{db_name=\"$db_name\"}[2m]) + idelta(oracle_sysstat_rollback_total{db_name=\"$db_name\"}[2m]))",
       "legendFormat": "per transaction"
      }
     ]
    },
    {
     "title": "User Calls",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "idelta(oracle_sysstat_useralls_total{db_name=\"$db_name\"}[2m])"
      },
      {
       "expr": "idelta(oracle_sysstat_useralls_total{db_name=\"$db_name\"}[2m]) / (idelta(oracle_sysstat_commit_total{db_name=\"$db_name\"}[2m]) + idelta(oracle_sysstat_rollback_total{db_name=\"$db_name\"}[2m]))",
       "legendFormat": "per transaction"
      }
     ]
    },
    {
     "title": "Parser",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "idelta(oracle_sysstat_parse_total{db_name=\"$db_name\"}[2m])"
      },
      {
       "expr": "idelta(oracle_sysstat_parse_total{db_name=\"$db_name\"}[2m]) / (idelta(oracle_sysstat_commit_total{db_name=\"$db_name\"}[2m]) + idelta(oracle_sysstat_rollback_total{db_name=\"$db_name\"}[2m]))",
       "legendFormat": "per tramsactopm"
      }
     ]
    },
    {
     "title": "Block Change",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "idelta(oracle_sysstat_dbblockchanges_total{db_name=\"$db_name\"}[3m])"
      },
      {
       "expr": "idelta(oracle_sysstat_dbblockchanges_total{db_name=\"$db_name\"}[3m]) / (idelta(oracle_sysstat_commit_total{db_name=\"$db_name\"}[2m]) + idelta(oracle_sysstat_rollback_total{db_name=\"$db_name\"}[2m]))",
       "legendFormat": "per transaction"
      }
     ]
    },
    {
     "title": "Physical Writes",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "idelta(oracle_sysstat_physicalwrites_total{db_name=\"$db_name\"}[2m])"
      },
      {
       "expr": "idelta(oracle_sysstat_physicalwrites_total{db_name=\"$db_name\"}[2m]) / (idelta(oracle_sysstat_commit_total{db_name=\"$db_name\"}[2m]) + idelta(oracle_sysstat_rollback_total{db_name=\"$db_name\"}[2m]))",
       "legendFormat": "per tramsactopm"
      }
     ]
    },
    {
     "title": "Physical Reads",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "idelta(oracle_sysstat_physicalreads_total{db_name=\"$db_name\"}[3m])"
      },
      {
       "expr": "idelta(oracle_sysstat_physicalreads_total{db_name=\"$db_name\"}[3m]) / (idelta(oracle_sysstat_commit_total{db_name=\"$db_name\"}[2m]) + idelta(oracle_sysstat_rollback_total{db_name=\"$db_name\"}[2m]))",
       "legendFormat": "per transaction"
      }
     ]
    },
    {
     "title": "Parser Hard",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "idelta(oracle_sysstat_parsehard_total{db_name=\"$db_name\"}[2m])"
      },
      {
       "expr": "idelta(oracle_sysstat_parsehard_total{db_name=\"$db_name\"}[2m]) / (idelta(oracle_sysstat_commit_total{db_name=\"$db_name\"}[2m]) + idelta(oracle_sysstat_rollback_total{db_name=\"$db_name\"}[2m]))",
       "legendFormat": "per transaction"
      }
     ]
    }
   ]
  },
  {
   "title": "Tablespace statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Large Write/Read MBytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "idelta(oracle_datafile_large_read_megabytes_total{db_name=\"$db_name\"}[2m])",
       "legendFormat": "{{tablespace}} large read "
      },
      {
       "expr": "idelta(oracle_datafile_large_write_megabytes_total{db_name=\"$db_name\"}[2m])",
       "legendFormat": "{{tablespace}} large write"
      }
     ]
    },
    {
     "title": "Small Read/Write MBytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "idelta(oracle_datafile_small_read_megabytes_total{db_name=\"$db_name\"}[2m])",
       "legendFormat": "{{tablespace}} small read "
      },
      {
       "expr": "idelta(oracle_datafile_small_write_megabytes_total{db_name=\"$db_name\"}[2m])",
       "legendFormat": "{{tablespace}} small write"
      }
     ]
    },
    {
     "title": "Tablespace Free",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "oracle_tablespace_free{db_name=\"$db_name\"}",
       "legendFormat": "{{tablespace}}"
      },
      {}
     ]
    },
    {
     "title": "Tablespace Used",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "oracle_tablespace_bytes{db_name=\"$db_name\"}",
       "legendFormat": "{{tablespace}}"
      }
     ]
    },
    {
     "title": "tablespace increase",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "increase(oracle_tablespace_bytes{db_name=\"$db_name\"}[1h])",
       "legendFormat": "{{tablespace}}"
      }
     ]
    },
    {
     "title": "DB Time for schema",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "idelta(oracle_sesstat_dbtime_total{db_name=\"$db_name\"}[2m])",
       "legendFormat": "{{username}}"
      }
     ]
    }
   ]
  }
 ]
}