{
 "title": "Alerts",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Oracle User Physical Read Total Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "oracle_user_disk_read_sum{username!=\"SYS\"}",
     "legendFormat": "{{db_name}} - {{inst}} - {{username}}"
    }
   ]
  },
  {
   "title": "Oracle Physical Read Total Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{name=\"physical read bytes\"}[2m])",
     "legendFormat": "{{db_name}} - {{inst}}"
    }
   ]
  },
  {
   "title": "I/O now",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_disk_io_now)by(node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Oracle Write Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{name=\"physical write total bytes\"}[2m])",
     "legendFormat": "{{db_name}} - {{inst}}"
    }
   ]
  },
  {
   "title": "log file sync",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{event=\"log file sync\", db_name!=\"report\", db_name!=\"dwdata\"}[2m]) / idelta(oracle_sysevent_waits_total{event=\"log file sync\", db_name!=\"report\", db_name!=\"dwdata\"}[2m]) / 1000",
     "legendFormat": "{{db_name}} - {{inst}}"
    }
   ]
  }
 ]
}