{
 "title": "Global IO Analyze",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "node_name", "query": "label_values(up,node_name)" }
  ]
 },
 "panels": [
  {
   "title": "node_disk_io_time_seconds_total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(node_disk_io_time_seconds_total{node_name=~\"$node_name\"}[2m]))by(node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "io_now",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_disk_io_now{node_name=~\"$node_name\"})by(node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "node_disk_write_time_seconds_total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(node_disk_write_time_seconds_total{node_name=~\"$node_name\"}[2m]))by(node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "node_disk_read_time_seconds_total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(node_disk_read_time_seconds_total{node_name=~\"$node_name\"}[2m]))by(node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "node_disk_writes_completed_total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(node_disk_writes_completed_total{node_name=~\"$node_name\"}[2m]))by(node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "node_disk_reads_completed_total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(node_disk_reads_completed_total{node_name=~\"$node_name\"}[2m]))by(node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "node_disk_writes_merged_total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(node_disk_writes_merged_total{node_name=~\"$node_name\"}[2m]))by(node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "node_disk_reads_merged_total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(node_disk_reads_merged_total{node_name=~\"$node_name\"}[2m]))by(node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "node_disk_written_bytes_total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(node_disk_written_bytes_total{node_name=~\"$node_name\"}[2m]))by(node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "node_disk_read_bytes_total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(node_disk_read_bytes_total{node_name=~\"$node_name\"}[2m]))by(node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  }
 ]
}