{
 "title": "Oracle All Server",
 "tags": [ "oracle" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "2m,3m,4m,5m,10m,15m, 20m, 30m,1h, 2h, 3h, 4h, 6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "node_name",
    "query": "query_result(count(label_join(oracle_up, \"node_name\", \"-\", \"db_name\", \"inst\"))by(node_name) )"
   }
  ]
 },
 "panels": [
  {
   "title": "load1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(label_replace(node_load1, \"node_name\", \"${1}-${2}1\", \"node_name\", \"^([a-z]*)([0-9]??)$\"),\"node_name\",\"$1-$2\",\"node_name\",\"^([a-z]*)-([0-9]?).*$\")",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "DB Time [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_time_model{name=\"DB time\"}[2m])",
     "legendFormat": "{{db_name}} - {{inst}}"
    }
   ]
  },
  {
   "title": "(Standard Deviation / Avg ) [$interval] {$node_name}",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "stddev_over_time(node_load1[$interval]) / avg_over_time(node_load1[$interval]) * 100",
     "legendFormat": "{{node_name}}"
    },
    {
     "expr": "avg_over_time(node_load1[$interval]) ",
     "legendFormat": "avg - {{node_name}}"
    }
   ]
  }
 ]
}