{
 "title": "Oracle Tablespace",
 "tags": [ "tablespace" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "db_name",
    "label": "db_name",
    "query": "label_values(oracle_up, db_name)"
   },
   {
    "name": "tablespace",
    "query": "label_values(oracle_tablespace_alloc_free_bytes{db_name=\"$db_name\", inst=\"1\"}, tablespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Tablespace",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "oracle_tablespace_alloc_free_bytes{db_name=\"$db_name\", tablespace=~\"$tablespace\", inst=\"1\"}",
     "legendFormat": "free - {{ tablespace }}"
    }
   ]
  },
  {
   "title": "Large Write/Read MBytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_datafile_large_read_megabytes_total{db_name=\"$db_name\", inst=\"$inst\"}[2m])",
     "legendFormat": "{{tablespace}} large read "
    },
    {
     "expr": "idelta(oracle_datafile_large_write_megabytes_total{db_name=\"$db_name\", inst=\"$inst\"}[2m])",
     "legendFormat": "{{tablespace}} large write"
    }
   ]
  },
  {
   "title": "Small Read/Write MBytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_datafile_small_read_megabytes_total{db_name=\"$db_name\", inst=\"$inst\"}[2m])",
     "legendFormat": "{{tablespace}} small read "
    },
    {
     "expr": "idelta(oracle_datafile_small_write_megabytes_total{db_name=\"$db_name\", inst=\"$inst\"}[2m])",
     "legendFormat": "{{tablespace}} small write"
    }
   ]
  }
 ]
}