{
 "title": "Oracle User Overview",
 "tags": [
  "oracle",
  "user"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "db_name",
    "label": "db_name",
    "query": "label_values(oracle_up, db_name)"
   },
   {
    "name": "inst",
    "query": "label_values(oracle_up{db_name=\"$db_name\"}, inst)"
   },
   {
    "name": "username",
    "label": "username",
    "query": "label_values(oracle_sql_executions_total{db_name=\"$db_name\", inst=\"$inst\"}, username)"
   },
   {
    "name": "interval",
    "query": "2m,3m,4m,5m,10m,15m,20m,30m,40m,50m,1h,2h,3h,4h,5h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Command Status Executes [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_sql_executions_total{db_name=\"$db_name\", inst=~\"$inst\", username=\"$username\"}[2m])) by(inst,command,username)",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "DB time [1min]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "oracle_session_time_model_sum{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"} > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top 5 ASH Event SQL [$interval]",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "topk(5,sum(count_over_time(oracle_ash_sample{db_name=\"$db_name\", inst=~\"$inst\", username=\"$username\" , sql_id!=\"null\"}[$interval])) by(username,event,sql_id,inst,opname))"
    }
   ]
  },
  {
   "title": "Executeions [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_session_statistic{db_name=\"$db_name\", inst=\"$inst\", username=\"$username\", name=\"execute count\"}[2m])) by(db_name,inst,username,name)",
     "legendFormat": "{{inst}}"
    }
   ]
  },
  {
   "title": "Session / Active Session [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oracle_active_session_user_max_seconds{db_name=\"$db_name\",inst=\"$inst\",username=\"$username\"}",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Top Event ($interval)",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(oracle_sessevent_waited_time_total{db_name=\"$db_name\", class!=\"Idle\", inst=~\"$inst\", username=\"$username\"}[$interval])) by (event) > 0",
     "legendFormat": "waits"
    },
    {
     "expr": "sum(increase(oracle_sessevent_waits_total{db_name=\"$db_name\", class!=\"Idle\", inst=~\"$inst\", username=\"$username\"}[$interval])) by (event) > 0"
    },
    {
     "expr": "(sum(increase(oracle_sessevent_waited_time_total{db_name=\"$db_name\", class!=\"Idle\", inst=~\"$inst\", username=\"$username\"}[$interval])) by (event)) / (sum(increase(oracle_sessevent_waits_total{db_name=\"$db_name\", class!=\"Idle\", inst=~\"$inst\", username=\"$username\"}[$interval])) by (event) >= 1)"
    }
   ]
  },
  {
   "title": "Commit / Rollback [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_session_statistic{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\", name=\"user commits\"}[2m]))",
     "legendFormat": "commit"
    },
    {
     "expr": "sum(idelta(oracle_session_statistic{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\", name=\"user rollbacks\"}[2m]))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Redo / Rate [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_session_statistic{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\", name=\"redo size\"}[2m]))",
     "legendFormat": "per min"
    },
    {
     "expr": "sum(irate(oracle_session_statistic{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\", name=\"redo size\"}[2m]))",
     "legendFormat": "per sec"
    }
   ]
  },
  {
   "title": "Top elapsed time SQL [$interval]",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": " increase(oracle_sql_elapsed_time_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[$interval]) and changes(oracle_sql_executions_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[$interval]) >= 2"
    },
    {
     "expr": "increase(oracle_sql_executions_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[$interval]) and changes(oracle_sql_executions_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[$interval]) >= 2"
    },
    {
     "expr": "increase(oracle_sql_elapsed_time_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[$interval]) / (increase(oracle_sql_executions_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[$interval]) and changes(oracle_sql_executions_total{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"}[$interval]) >= 2)",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "parse count (total) [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_session_statistic{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\", name=\"parse count (total)\"}[2m]))",
     "legendFormat": "parse count total"
    }
   ]
  },
  {
   "title": "Read/Write Bytes Total / 1 min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_session_statistic{db_name=\"$db_name\", inst=~\"$inst\", username=\"$username\", name=\"physical read total bytes\"}[2m]))",
     "legendFormat": "read bytes"
    },
    {
     "expr": "sum(idelta(oracle_session_statistic{db_name=\"$db_name\", inst=~\"$inst\", username=\"$username\", name=\"physical write total bytes\"}[2m]))",
     "legendFormat": "writes bytes"
    }
   ]
  },
  {
   "title": "parse count (hard) [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_session_statistic{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\", name=\"parse count (hard)\"}[2m]))",
     "legendFormat": "parse count total"
    }
   ]
  },
  {
   "title": "leaf node splits [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_session_statistic{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\", name=\"leaf node splits\"}[2m]))",
     "legendFormat": "parse count total"
    }
   ]
  },
  {
   "title": "Session Wait [$interval]",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "increase(oracle_sessevent_waited_time_total{db_name=\"$db_name\", username=\"$username\", class!=\"Idle\", inst=\"$inst\"}[$interval]) / (increase(oracle_sessevent_waits_total{db_name=\"$db_name\", username=\"$username\", class!=\"Idle\", inst=\"$inst\"}[$interval]) and changes(oracle_sessevent_waits_total{db_name=\"$db_name\", username=\"$username\", class!=\"Idle\", inst=\"$inst\"}[$interval]) >= 2)"
    },
    {
     "expr": "increase(oracle_sessevent_waits_total{db_name=\"$db_name\", username=\"$username\", class!=\"Idle\", inst=\"$inst\"}[$interval]) and changes(oracle_sessevent_waits_total{db_name=\"$db_name\", username=\"$username\", class!=\"Idle\", inst=\"$inst\"}[$interval]) >= 2"
    }
   ]
  },
  {
   "title": "leaf node 90-10 splits [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_session_statistic{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\", name=\"leaf node 90-10 splits\"}[2m]))",
     "legendFormat": "parse count total"
    }
   ]
  },
  {
   "title": "Long Session rate",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(oracle_session{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\"})",
     "legendFormat": "current point session"
    },
    {
     "expr": "count(count_over_time(oracle_session_statistic{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\", name=\"user commits\"}[2m]) == 2)",
     "legendFormat": "2m long session"
    },
    {
     "expr": "count(count_over_time(oracle_session_statistic{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\", name=\"user commits\"}[3m]) == 3)",
     "legendFormat": "3m long session"
    },
    {
     "expr": "count(count_over_time(oracle_session_statistic{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\", name=\"user commits\"}[5m]) == 5)",
     "legendFormat": "5m long session"
    },
    {
     "expr": "count(count_over_time(oracle_session_statistic{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\", name=\"user commits\"}[10m]) == 10)",
     "legendFormat": "10m long session"
    },
    {
     "expr": "count(count_over_time(oracle_session_statistic{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\", name=\"user commits\"}[30m]) == 30)",
     "legendFormat": "30m long session"
    },
    {
     "expr": "count(count_over_time(oracle_session_statistic{db_name=\"$db_name\", username=\"$username\", inst=\"$inst\", name=\"user commits\"}[60m]) == 60)",
     "legendFormat": "60m long session"
    }
   ]
  }
 ]
}