{
 "title": "Oracle Overview",
 "description": "oracledb dashboard",
 "tags": [
  "oracle",
  "overview"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "db_name",
    "query": "label_values(oracle_up, db_name)"
   },
   {
    "name": "inst",
    "query": "label_values(oracle_up{db_name=\"$db_name\"}, inst)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "2m,3m,5m,10m,15m,20m,30m,1h,2h,3h,4h,5h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "DB Time for Schema [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_session_time_model{db_name=\"$db_name\", inst=~\"$inst\", name=\"DB time\"}[2m])) by (username, inst) > 0 ",
     "legendFormat": "{{inst}} - {{username}}"
    }
   ]
  },
  {
   "title": "DB Time for Schema($interval)",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(oracle_session_time_model{db_name=\"$db_name\", inst=~\"$inst\", name=\"DB time\"}[$interval])) by (username, inst)"
    }
   ]
  },
  {
   "title": "DB Time [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_time_model{db_name=\"$db_name\", inst=~\"$inst\"}[2m]) >= 1",
     "legendFormat": "{{name}} - {{inst}}"
    }
   ]
  },
  {
   "title": "Session / Active Session [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oracle_active_session_max_seconds{db_name=\"$db_name\",inst=~\"$inst\"}",
     "legendFormat": "{{inst}}"
    },
    {
     "expr": "avg(sum(oracle_ash_sample{db_name=\"$db_name\",inst=~\"$inst\"})by(db_name,inst,sample_id))by(db_name,inst)",
     "legendFormat": "{{inst}} - avg"
    }
   ]
  },
  {
   "title": "Top System Event ($interval)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "increase(oracle_sysevent_waits_total{db_name=\"$db_name\", class!=\"Idle\", inst=~\"$inst\"}[$interval]) and changes(oracle_sysevent_waits_total{db_name=\"$db_name\", class!=\"Idle\", inst=~\"$inst\"}[$interval]) >= 2",
     "legendFormat": "waits"
    },
    {
     "expr": "increase(oracle_sysevent_waited_time_total{db_name=\"$db_name\", class!=\"Idle\", inst=~\"$inst\"}[$interval]) and changes(oracle_sysevent_waits_total{db_name=\"$db_name\", class!=\"Idle\", inst=~\"$inst\"}[$interval]) >= 2",
     "legendFormat": "waited time"
    },
    {
     "expr": "increase(oracle_sysevent_waited_time_total{db_name=\"$db_name\", class!=\"Idle\", inst=~\"$inst\"}[$interval]) / (increase(oracle_sysevent_waits_total{db_name=\"$db_name\", class!=\"Idle\", inst=~\"$inst\"}[$interval]) and changes(oracle_sysevent_waits_total{db_name=\"$db_name\", class!=\"Idle\", inst=~\"$inst\"}[$interval]) >= 2)"
    }
   ]
  },
  {
   "title": "Commit & Rollback [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=~\"$inst\", name=\"user commits\"}[2m])",
     "legendFormat": "{{inst}} - commit"
    },
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=~\"$inst\", name=\"user rollbacks\"}[2m])",
     "legendFormat": "{{inst}} - rollback"
    }
   ]
  },
  {
   "title": "Execute Count [1m]",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(oracle_system_statistic{db_name=\"$db_name\", inst=~\"$inst\", name=\"execute count\"}[2m])",
     "legendFormat": "{{inst}}"
    }
   ]
  },
  {
   "title": "ASH Top Event[$interval]",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(count_over_time(oracle_ash_sample{db_name=\"$db_name\", inst=~\"$inst\", username!=\"SYS\"}[$interval])) by(username,event,sql_id,inst,opname)"
    }
   ]
  },
  {
   "title": "Read/Write Bytes Total / 1 min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=~\"$inst\", name=\"physical read total bytes\"}[5m])",
     "legendFormat": "{{inst}} - read bytes"
    },
    {
     "expr": "idelta(oracle_system_statistic{db_name=\"$db_name\", inst=~\"$inst\", name=\"physical write total bytes\"}[5m])",
     "legendFormat": "{{inst}} - write bytes"
    }
   ]
  },
  {
   "title": "Redo Size/s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(oracle_system_statistic{db_name=\"$db_name\", inst=~\"$inst\",name=\"redo size\"}[2m])",
     "legendFormat": "{{inst}}"
    }
   ]
  },
  {
   "title": "Log Switch [1h]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(idelta(oracle_log_sequence{db_name=\"$db_name\", inst=~\"$inst\"}[2m])) >= 1",
     "legendFormat": "{{inst}}"
    }
   ]
  },
  {
   "title": "System Command Executions State [1m]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(oracle_sql_executions_total{db_name=\"$db_name\", inst=~\"$inst\"}[2m])) by (command, inst)",
     "legendFormat": "{{inst}} - {{command}}"
    }
   ]
  },
  {
   "title": "Session For User",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(oracle_session{db_name=\"$db_name\", inst=~\"$inst\", username!=\"null\"}) by (inst, username)",
     "legendFormat": "{{inst}} - {{username}}"
    }
   ]
  }
 ]
}