{
 "title": "Temp",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Disk Write Bytes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(node_disk_written_bytes_total[2m])) by(node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(node_disk_read_bytes_total[2m])) by(node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "log file sync",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "idelta(oracle_sysevent_waited_time_total{event=\"log file sync\", db_name!=\"report\"}[2m]) / idelta(oracle_sysevent_waits_total{event=\"log file sync\", db_name!=\"report\"}[2m])",
     "legendFormat": "{{db_name}} - {{inst}}"
    }
   ]
  }
 ]
}