name: build
on: 
  push:
    paths: 
      - VERSION
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get and Set Version
        id: version
        run: |
           version=`cat VERSION`
           echo "::set-output name=version::${version}"
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            shinhwagk/oracle_exporter:${{ steps.version.outputs.version }}
            shinhwagk/oracle_exporter:latest