name: build
on: 
  push:
    tags:
      - v1.*
jobs:
  build:
    runs-on: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15.5
      - run: |
          version=`cat VERSION`
          docker build -t shinhwagk/oracle_exporter:$version .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag shinhwagk/oracle_exporter:$version shinhwagk/oracle_exporter:latest
          docker push shinhwagk/oracle_exporter:$version
          docker push shinhwagk/oracle_exporter:latest