name: cd

on:
  push:
    paths:
      - VERSION
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          version=`cat VERSION`
          docker build -t shinhwagk/oracle_exporter:$version .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag shinhwagk/oracle_exporter:$version shinhwagk/oracle_exporter:latest
          docker push shinhwagk/oracle_exporter:$version
          docker push shinhwagk/oracle_exporter:latest
