name: test

on: push
      
jobs:
  test:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    container:
      image: shinhwagk/oraclepython
    services:
      oracle11g:
        image: gvenzl/oracle-xe:latest
        env:
          ORACLE_PASSWORD: ORACLE_PASSWORD
        ports:
          - 49161:1521
    steps:
      - name: Check out the repo
        run: |
          cat /etc/redhat* && sqlplus system/ORACLE_PASSWORD@oracle11g:${{ job.services.oracle11g.ports[49161] }}/XEPDB1 <<EOF
          select * from dual;
          exit
          EOF
