name: test

on: push

jobs:
  test:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    container: node:16
    # container:
    #   image: shinhwagk/oraclepython
    services:
      oracle11g:
        image: gvenzl/oracle-xe:latest
        env:
          ORACLE_PASSWORD: ORACLE_PASSWORD
        ports:
          - 1521:1521
      mdb:
        image: shinhwagk/multidatabase
        env:
          ORACLE_USERPASS: system:ORACLE_PASSWORD
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18.0"
      - run: |
          curl http://mdb:5000/check
          go run main.go mdb.go mp.go --mdb.addr=mdb:5000 --file.metrics=https://raw.githubusercontent.com/shinhwagk/oracle_exporter/mdb/yaml/test.yaml &
          sleep 30
          curl -g -s 'http://127.0.0.1:9521/metrics?collect[]=system-timemodel&dsn=oracle11g:1521/XEPDB1' | grep 'oracle_up 1'
