name: test

on: push
      
jobs:
  test:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    container:
      image: shinhwagk/oraclepython
    services:
      oracle11g:
        image: wnameless/oracle-xe-11g-r2
        env:
          ORACLE_ALLOW_REMOTE: true
        ports:
          - 1521:1521
    steps:
      - name: Check out the repo
        run: |
          cat /etc/redhat* && sqlplus system/oracle@oracle11g:${{ job.services.oracle11g.ports[1521] }}:xe <<EOF
          select * from dual;
          exit
          EOF
